import { open } from './harness.mjs'
const app = await open()
await app.reset()
await app.type(['alpha', 'beta', 'gamma'])
const lines = app.page.locator('.tiptap.ProseMirror.mindflow-editor:not(.is-line) > p')
await lines.nth(2).hover(); await app.page.waitForTimeout(150)
const grip = app.page.locator('.tiptap-drag-handle-grip')
const g = await grip.boundingBox()
const a = await lines.nth(0).boundingBox()
console.log('alpha box', JSON.stringify(a))
for (const frac of [0.5, 0.25, 0.05, -0.3]) {
  await app.reset(); await app.type(['alpha', 'beta', 'gamma'])
  await lines.nth(2).hover(); await app.page.waitForTimeout(150)
  const gg = await grip.boundingBox(); const aa = await lines.nth(0).boundingBox()
  await app.page.mouse.move(gg.x + gg.width / 2, gg.y + gg.height / 2)
  await app.page.mouse.down()
  await app.page.mouse.move(aa.x + 40, aa.y + aa.height * frac, { steps: 12 })
  await app.page.waitForTimeout(120)
  await app.page.mouse.up(); await app.page.waitForTimeout(250)
  console.log(`frac ${frac}:`, (await app.shape()).replace(/\n/g, ' | '))
}
await app.close(); process.exit(0)
